### POST request to backend
POST https://127.0.0.1:4442/submit/
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "message": "hello :)"
}

###

### GET request to backend
GET https://127.0.0.1:4442/recipe/
Content-Type: application/json

{
  "input": "https://www.allrecipes.com/recipe/25871/grilled-fish-steaks/"
}
###